apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins-deployment
  template:
    metadata:
      labels:
        app: jenkins-deployment
    spec:
      containers:
        - name: jenkins-container
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_2f190448ce7e
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
      volumes:
        - name: jenkins-home
          hostPath:
            path: config